// This object controls the exporting of the goal model to various formats
var EXPORTER = {
    /**
     * Export the goal model to XML
     */
    exportXml: function () {
        var a = document.createElement('a'); // The resulting file

        a.download = 'goals.svg';
        a.type = 'image/svg+xml';
        a.href = (window.URL || webkitURL).createObjectURL(new Blob(
            [PAPER.toSVG()], {type: "image/svg+xml"}));
        a.click();
    },

    /**
     * Export the goal model to PNG
     */
    exportPng: function () {
        var a = document.createElement('a'); // The file

        canvg('myCanvas', PAPER.toSVG()); // Bind the svg to the canvas
        a.download = 'goals.png';
        a.type = 'image/png';
        a.href = document.getElementById("myCanvas").toDataURL("image/png");
        a.click();
    },

    /**
     * Export the goal model to PDF
     */
    exportPdf: function () {
        /*var svgString = CANVAS.paper.toSVG(), // The svg generated by Raphael
            a = document.createElement('a'), // The resulting file
            blob; // A variable for the blob API

        a.download = 'goals.pdf';
        a.type = 'application/pdf';
        blob = new Blob([svgString], {type: "application/pdf"});
        a.href = (window.URL || webkitURL).createObjectURL(blob);
        a.click();*/
    }
}
